### ISSUE TITLE
Temperature inclusion

### ISSUE THREAD

**Issue by ChRen95** [pyroll-project/pyroll-linear-thermal-expansion#1]
When using the pyroll-ring-model-thermal and therefore, defining a in_profile using `core_temperature` and `surface_temperature` the plugin won't work since it hardcoded uses profile.temperature.

Suggested change would be to implement a check in the plugin to calculate the mean temperature inside the plugin.
If @axtimhaus has no other suggestions I would implement it like that.

**Comment by axtimhaus** [comment]
Why would you define a Profile with solely core and surface temperature? Where are the rings between? If you define all rings, it shall work, since `temperature` is calculated as a weighted mean of them

**Comment by ChRen95** [comment]
Availability of measurements is the magic therm. 
On can sometimes assume a temperature gradient over a profile but providing the ring temperatures from both values should be handled by the plugin

**Comment by axtimhaus** [comment]
But this is than a matter of the ring model, not of linear expansion. There you have to define an assumption whats happening inside, when only core and surface are given

**Comment by axtimhaus** [comment]
Linear expansion does not know anything about rings. It is just working with mean temperature by design. If desired on a per-ring basis, make a new plugin `pyroll-ring-model-thermal-expansion` or similar.
